### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by gtteixeira** [ycfu/BubGAN#2]
Hello. During file compilation, there was an error on line 69 of the Main_ImageGeneration file and it was not possible to complete the compilation.
Thanks.
![image](https://user-images.githubusercontent.com/28991408/100396245-35d3e580-3023-11eb-9154-687eb534fe42.png)

**Comment by ycfu** [comment]
Hi gtteixeira, 
The boolean function  is defined by Simulink in Matlab.  The error can occur if the Simulink is not installed with Matlab.  Alternatively, you can try to use logical function.

**Comment by gtteixeira** [comment]
Thanks for your help ycfu. I will check that.Enviado do meu Galaxy
-------- Mensagem original --------De : ycfu <notifications@github.com> Data: 26/11/2020  21:35  (GMT-03:00) Para: ycfu/BubGAN <BubGAN@noreply.github.com> Cc: GTTeixeira <glebertt@yahoo.com.br>, Author <author@noreply.github.com> Assunto: Re: [ycfu/BubGAN] Error during compilation (#2) 
Hi gtteixeira,
The boolean function  is defined by Simulink in Matlab.  The error can occur if the Simulink is not installed with Matlab.  Alternatively, you can try to use logical function.
