### ISSUE TITLE
AspectRatio control problem

### ISSUE THREAD

**Issue by tgreen443** [ycfu/BubGAN#4]
Dear Mr.Fu,
I have add some code in BubDisribution.m to control the AspectRatio of bubble generation. It looks like this :   

`       

        elseif strcmp(ParaImg.BubSizeMode,'flat') 
         r=normrnd(BubRefSize/2,BubDev/2);
        AspectRatio=rand*MaxAspectRatio;
        a=r*sqrt(AspectRatio);
        b=r/(sqrt(AspectRatio));
         while a<0 | b<0   % reject negative semi-axis and redo
            r=normrnd(BubRefSize/2,BubDev/2);
            AspectRatio=rand*MaxAspectRatio;
            a=r*sqrt(AspectRatio);
            b=r/(sqrt(AspectRatio));
        end
`
I set the bubbles very flat And I check the BubList in workspace ,All the a and b value is well controlled, however some bubble with low AspectRatio  (b/a),looks very close to a positive circle on the picture generated by the code .
![image](https://github.com/ycfu/BubGAN/assets/60002376/abba254e-1b38-43e2-9033-86db5fd068f5)
![image](https://github.com/ycfu/BubGAN/assets/60002376/70d230ea-1473-4576-97fd-cd100274b5de)
would you mind giving me some advice , Thanks a lot!

**Comment by ycfu** [comment]
In our investigations of bubbly flow conditions, it's been observed that bubbles with extremely low aspect ratios (below 0.1) are infrequent. The BubGAN algorithm is primarily trained for the more common bubble geometries we've encountered, so it might not perform optimally for these rarer, flatter bubbles. This limitation could be causing inaccuracies in the interpolation of the latent vector, leading to the visual discrepancy you noticed where some bubbles with low aspect ratios appear more circular than intended in the generated images.

**Comment by tgreen443** [comment]
Thanks for your patient reply!
Yes , as you mentioned, extrem aspect ratios are not that common in bubbly flow . It is because the pictures that the Bubgan ganerated always remain some bubbles quite " positive circle ", positive circle bubbles are also rarely obseverd in our experimental bubbly flow .
![image](https://github.com/ycfu/BubGAN/assets/60002376/269349f9-58f5-479b-a7a2-a32a0081ee16)

So I try to make their aspect ratios lower than 0.5 to make them flatter.But some bubbles are still not flat .So I make aspect ratios extrem lower to see what will happen.
As you mentioned , Is it because the algorithm  itself that we cannot get pictures without circle bubbles?
Thanks!

**Comment by ycfu** [comment]
No problem. If your flow conditions and bubble characteristics are quite differ from our specific conditions, I would recommend training the Generative Adversarial Network (GAN) using your own dataset of bubble data. This approach would enable you to generate synthetic bubble morphologies that are tailored to your specific research needs and more accurately represent the conditions you are studying.
